namespace Calculator
{
    partial class Form1
    {
        /// <summary>
        /// 設計工具所需的變數。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 清除任何使用中的資源。
        /// </summary>
        /// <param name="disposing">如果應該處置受控資源則為 true，否則為 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form 設計工具產生的程式碼

        /// <summary>
        /// 此為設計工具支援所需的方法 - 請勿使用程式碼編輯器修改
        /// 這個方法的內容。
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties161 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties162 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties163 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties164 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties165 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties166 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties167 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties168 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties169 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties170 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties171 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties172 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties173 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties174 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties175 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties176 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties177 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties178 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties179 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties180 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties181 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties182 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties183 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties184 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties185 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties186 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties187 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties188 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties189 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties190 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties191 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties192 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties199 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties200 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties197 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties198 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties195 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties196 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties193 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties194 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.equal_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Multiply_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Less_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.double_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Divide_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.add_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.close_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CE_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.C_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Quotient_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.num7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.num0 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label3 = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Black;
            this.panel1.Controls.Add(this.pictureBox2);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(396, 31);
            this.panel1.TabIndex = 1;
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackgroundImage = global::Calculator.Properties.Resources.icons8_delete_32;
            this.pictureBox2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.pictureBox2.Location = new System.Drawing.Point(368, 0);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(29, 31);
            this.pictureBox2.TabIndex = 22;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.Exitbtn_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImage = global::Calculator.Properties.Resources.icons8_calculator_32;
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(29, 31);
            this.pictureBox1.TabIndex = 21;
            this.pictureBox1.TabStop = false;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(25, 5);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(57, 20);
            this.label2.TabIndex = 0;
            this.label2.Text = "計算機";
            // 
            // label1
            // 
            this.label1.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.label1.Font = new System.Drawing.Font("Verdana", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(12, 86);
            this.label1.Name = "label1";
            this.label1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label1.Size = new System.Drawing.Size(376, 59);
            this.label1.TabIndex = 20;
            this.label1.Text = "0";
            // 
            // equal_btn
            // 
            this.equal_btn.AnimationSpeed = 220;
            this.equal_btn.BackColor = System.Drawing.Color.Transparent;
            this.equal_btn.BackColor1 = System.Drawing.Color.Teal;
            this.equal_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("equal_btn.BackgroundImage")));
            this.equal_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.equal_btn.ButtonText = "=";
            this.equal_btn.ButtonTextMarginLeft = 0;
            this.equal_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.equal_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.equal_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.equal_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.equal_btn.DisabledForecolor = System.Drawing.Color.Black;
            this.equal_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.equal_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.equal_btn.ForeColor = System.Drawing.Color.White;
            this.equal_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.equal_btn.IconPadding = 10;
            this.equal_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.equal_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.equal_btn.IdleBorderRadius = 1;
            this.equal_btn.IdleBorderThickness = 1;
            this.equal_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.equal_btn.IdleIconLeftImage = null;
            this.equal_btn.IdleIconRightImage = null;
            this.equal_btn.IndicateFocus = true;
            this.equal_btn.Location = new System.Drawing.Point(198, 573);
            this.equal_btn.Name = "equal_btn";
            stateProperties161.BorderColor = System.Drawing.Color.Teal;
            stateProperties161.BorderRadius = 1;
            stateProperties161.BorderThickness = 1;
            stateProperties161.FillColor = System.Drawing.Color.Teal;
            stateProperties161.ForeColor = System.Drawing.Color.White;
            stateProperties161.IconLeftImage = null;
            stateProperties161.IconRightImage = null;
            this.equal_btn.onHoverState = stateProperties161;
            stateProperties162.BorderColor = System.Drawing.Color.Teal;
            stateProperties162.BorderRadius = 1;
            stateProperties162.BorderThickness = 1;
            stateProperties162.FillColor = System.Drawing.Color.Teal;
            stateProperties162.ForeColor = System.Drawing.Color.White;
            stateProperties162.IconLeftImage = null;
            stateProperties162.IconRightImage = null;
            this.equal_btn.OnPressedState = stateProperties162;
            this.equal_btn.Size = new System.Drawing.Size(100, 100);
            this.equal_btn.TabIndex = 19;
            this.equal_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.equal_btn.TextMarginLeft = 0;
            this.equal_btn.Click += new System.EventHandler(this.Equal_btn_Click);
            // 
            // Multiply_btn
            // 
            this.Multiply_btn.AnimationSpeed = 220;
            this.Multiply_btn.BackColor = System.Drawing.Color.Transparent;
            this.Multiply_btn.BackColor1 = System.Drawing.Color.Teal;
            this.Multiply_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Multiply_btn.BackgroundImage")));
            this.Multiply_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.Multiply_btn.ButtonText = "*";
            this.Multiply_btn.ButtonTextMarginLeft = 0;
            this.Multiply_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Multiply_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Multiply_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.Multiply_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.Multiply_btn.DisabledForecolor = System.Drawing.Color.Black;
            this.Multiply_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Multiply_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Multiply_btn.ForeColor = System.Drawing.Color.White;
            this.Multiply_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Multiply_btn.IconPadding = 10;
            this.Multiply_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Multiply_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.Multiply_btn.IdleBorderRadius = 1;
            this.Multiply_btn.IdleBorderThickness = 1;
            this.Multiply_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.Multiply_btn.IdleIconLeftImage = null;
            this.Multiply_btn.IdleIconRightImage = null;
            this.Multiply_btn.IndicateFocus = true;
            this.Multiply_btn.Location = new System.Drawing.Point(297, 474);
            this.Multiply_btn.Name = "Multiply_btn";
            stateProperties163.BorderColor = System.Drawing.Color.Teal;
            stateProperties163.BorderRadius = 1;
            stateProperties163.BorderThickness = 1;
            stateProperties163.FillColor = System.Drawing.Color.Teal;
            stateProperties163.ForeColor = System.Drawing.Color.White;
            stateProperties163.IconLeftImage = null;
            stateProperties163.IconRightImage = null;
            this.Multiply_btn.onHoverState = stateProperties163;
            stateProperties164.BorderColor = System.Drawing.Color.Teal;
            stateProperties164.BorderRadius = 1;
            stateProperties164.BorderThickness = 1;
            stateProperties164.FillColor = System.Drawing.Color.Teal;
            stateProperties164.ForeColor = System.Drawing.Color.White;
            stateProperties164.IconLeftImage = null;
            stateProperties164.IconRightImage = null;
            this.Multiply_btn.OnPressedState = stateProperties164;
            this.Multiply_btn.Size = new System.Drawing.Size(100, 100);
            this.Multiply_btn.TabIndex = 18;
            this.Multiply_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Multiply_btn.TextMarginLeft = 0;
            this.Multiply_btn.Click += new System.EventHandler(this.Multiply_btn_Click);
            // 
            // Less_btn
            // 
            this.Less_btn.AnimationSpeed = 220;
            this.Less_btn.BackColor = System.Drawing.Color.Transparent;
            this.Less_btn.BackColor1 = System.Drawing.Color.Teal;
            this.Less_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Less_btn.BackgroundImage")));
            this.Less_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.Less_btn.ButtonText = "-";
            this.Less_btn.ButtonTextMarginLeft = 0;
            this.Less_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Less_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Less_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.Less_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.Less_btn.DisabledForecolor = System.Drawing.Color.Black;
            this.Less_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Less_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Less_btn.ForeColor = System.Drawing.Color.White;
            this.Less_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Less_btn.IconPadding = 10;
            this.Less_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Less_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.Less_btn.IdleBorderRadius = 1;
            this.Less_btn.IdleBorderThickness = 1;
            this.Less_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.Less_btn.IdleIconLeftImage = null;
            this.Less_btn.IdleIconRightImage = null;
            this.Less_btn.IndicateFocus = true;
            this.Less_btn.Location = new System.Drawing.Point(297, 375);
            this.Less_btn.Name = "Less_btn";
            stateProperties165.BorderColor = System.Drawing.Color.Teal;
            stateProperties165.BorderRadius = 1;
            stateProperties165.BorderThickness = 1;
            stateProperties165.FillColor = System.Drawing.Color.Teal;
            stateProperties165.ForeColor = System.Drawing.Color.White;
            stateProperties165.IconLeftImage = null;
            stateProperties165.IconRightImage = null;
            this.Less_btn.onHoverState = stateProperties165;
            stateProperties166.BorderColor = System.Drawing.Color.Teal;
            stateProperties166.BorderRadius = 1;
            stateProperties166.BorderThickness = 1;
            stateProperties166.FillColor = System.Drawing.Color.Teal;
            stateProperties166.ForeColor = System.Drawing.Color.White;
            stateProperties166.IconLeftImage = null;
            stateProperties166.IconRightImage = null;
            this.Less_btn.OnPressedState = stateProperties166;
            this.Less_btn.Size = new System.Drawing.Size(100, 100);
            this.Less_btn.TabIndex = 17;
            this.Less_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Less_btn.TextMarginLeft = 0;
            this.Less_btn.Click += new System.EventHandler(this.Less_btn_Click);
            // 
            // double_btn
            // 
            this.double_btn.AnimationSpeed = 220;
            this.double_btn.BackColor = System.Drawing.Color.Transparent;
            this.double_btn.BackColor1 = System.Drawing.Color.DimGray;
            this.double_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("double_btn.BackgroundImage")));
            this.double_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.double_btn.ButtonText = ".";
            this.double_btn.ButtonTextMarginLeft = 0;
            this.double_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.double_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.double_btn.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.double_btn.DisabledFillColor = System.Drawing.Color.DimGray;
            this.double_btn.DisabledForecolor = System.Drawing.Color.DimGray;
            this.double_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.double_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.double_btn.ForeColor = System.Drawing.Color.White;
            this.double_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.double_btn.IconPadding = 10;
            this.double_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.double_btn.IdleBorderColor = System.Drawing.Color.DimGray;
            this.double_btn.IdleBorderRadius = 1;
            this.double_btn.IdleBorderThickness = 1;
            this.double_btn.IdleFillColor = System.Drawing.Color.DimGray;
            this.double_btn.IdleIconLeftImage = null;
            this.double_btn.IdleIconRightImage = null;
            this.double_btn.IndicateFocus = true;
            this.double_btn.Location = new System.Drawing.Point(0, 573);
            this.double_btn.Name = "double_btn";
            stateProperties167.BorderColor = System.Drawing.Color.DimGray;
            stateProperties167.BorderRadius = 1;
            stateProperties167.BorderThickness = 1;
            stateProperties167.FillColor = System.Drawing.Color.DimGray;
            stateProperties167.ForeColor = System.Drawing.Color.White;
            stateProperties167.IconLeftImage = null;
            stateProperties167.IconRightImage = null;
            this.double_btn.onHoverState = stateProperties167;
            stateProperties168.BorderColor = System.Drawing.Color.DimGray;
            stateProperties168.BorderRadius = 1;
            stateProperties168.BorderThickness = 1;
            stateProperties168.FillColor = System.Drawing.Color.DimGray;
            stateProperties168.ForeColor = System.Drawing.Color.White;
            stateProperties168.IconLeftImage = null;
            stateProperties168.IconRightImage = null;
            this.double_btn.OnPressedState = stateProperties168;
            this.double_btn.Size = new System.Drawing.Size(100, 100);
            this.double_btn.TabIndex = 16;
            this.double_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.double_btn.TextMarginLeft = 0;
            this.double_btn.Click += new System.EventHandler(this.Double_btn_Click);
            // 
            // Divide_btn
            // 
            this.Divide_btn.AnimationSpeed = 220;
            this.Divide_btn.BackColor = System.Drawing.Color.Transparent;
            this.Divide_btn.BackColor1 = System.Drawing.Color.Teal;
            this.Divide_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Divide_btn.BackgroundImage")));
            this.Divide_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.Divide_btn.ButtonText = "/";
            this.Divide_btn.ButtonTextMarginLeft = 0;
            this.Divide_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Divide_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Divide_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.Divide_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.Divide_btn.DisabledForecolor = System.Drawing.Color.Black;
            this.Divide_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Divide_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Divide_btn.ForeColor = System.Drawing.Color.White;
            this.Divide_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Divide_btn.IconPadding = 10;
            this.Divide_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Divide_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.Divide_btn.IdleBorderRadius = 1;
            this.Divide_btn.IdleBorderThickness = 1;
            this.Divide_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.Divide_btn.IdleIconLeftImage = null;
            this.Divide_btn.IdleIconRightImage = null;
            this.Divide_btn.IndicateFocus = true;
            this.Divide_btn.Location = new System.Drawing.Point(297, 573);
            this.Divide_btn.Name = "Divide_btn";
            stateProperties169.BorderColor = System.Drawing.Color.Teal;
            stateProperties169.BorderRadius = 1;
            stateProperties169.BorderThickness = 1;
            stateProperties169.FillColor = System.Drawing.Color.Teal;
            stateProperties169.ForeColor = System.Drawing.Color.White;
            stateProperties169.IconLeftImage = null;
            stateProperties169.IconRightImage = null;
            this.Divide_btn.onHoverState = stateProperties169;
            stateProperties170.BorderColor = System.Drawing.Color.Teal;
            stateProperties170.BorderRadius = 1;
            stateProperties170.BorderThickness = 1;
            stateProperties170.FillColor = System.Drawing.Color.Teal;
            stateProperties170.ForeColor = System.Drawing.Color.White;
            stateProperties170.IconLeftImage = null;
            stateProperties170.IconRightImage = null;
            this.Divide_btn.OnPressedState = stateProperties170;
            this.Divide_btn.Size = new System.Drawing.Size(100, 100);
            this.Divide_btn.TabIndex = 13;
            this.Divide_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Divide_btn.TextMarginLeft = 0;
            this.Divide_btn.Click += new System.EventHandler(this.Divide_btn_Click);
            // 
            // add_btn
            // 
            this.add_btn.AnimationSpeed = 220;
            this.add_btn.BackColor = System.Drawing.Color.Transparent;
            this.add_btn.BackColor1 = System.Drawing.Color.Teal;
            this.add_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("add_btn.BackgroundImage")));
            this.add_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.add_btn.ButtonText = "+";
            this.add_btn.ButtonTextMarginLeft = 0;
            this.add_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.add_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.add_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.add_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.add_btn.DisabledForecolor = System.Drawing.Color.Black;
            this.add_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.add_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.add_btn.ForeColor = System.Drawing.Color.White;
            this.add_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.add_btn.IconPadding = 10;
            this.add_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.add_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.add_btn.IdleBorderRadius = 1;
            this.add_btn.IdleBorderThickness = 1;
            this.add_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.add_btn.IdleIconLeftImage = null;
            this.add_btn.IdleIconRightImage = null;
            this.add_btn.IndicateFocus = true;
            this.add_btn.Location = new System.Drawing.Point(297, 276);
            this.add_btn.Name = "add_btn";
            stateProperties171.BorderColor = System.Drawing.Color.Teal;
            stateProperties171.BorderRadius = 1;
            stateProperties171.BorderThickness = 1;
            stateProperties171.FillColor = System.Drawing.Color.Teal;
            stateProperties171.ForeColor = System.Drawing.Color.White;
            stateProperties171.IconLeftImage = null;
            stateProperties171.IconRightImage = null;
            this.add_btn.onHoverState = stateProperties171;
            stateProperties172.BorderColor = System.Drawing.Color.Teal;
            stateProperties172.BorderRadius = 1;
            stateProperties172.BorderThickness = 1;
            stateProperties172.FillColor = System.Drawing.Color.Teal;
            stateProperties172.ForeColor = System.Drawing.Color.White;
            stateProperties172.IconLeftImage = null;
            stateProperties172.IconRightImage = null;
            this.add_btn.OnPressedState = stateProperties172;
            this.add_btn.Size = new System.Drawing.Size(100, 100);
            this.add_btn.TabIndex = 12;
            this.add_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.add_btn.TextMarginLeft = 0;
            this.add_btn.Click += new System.EventHandler(this.Add_btn_Click);
            // 
            // num3
            // 
            this.num3.AnimationSpeed = 220;
            this.num3.BackColor = System.Drawing.Color.Transparent;
            this.num3.BackColor1 = System.Drawing.Color.DimGray;
            this.num3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num3.BackgroundImage")));
            this.num3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num3.ButtonText = "3";
            this.num3.ButtonTextMarginLeft = 0;
            this.num3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num3.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num3.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num3.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num3.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num3.ForeColor = System.Drawing.Color.White;
            this.num3.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num3.IconPadding = 10;
            this.num3.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num3.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num3.IdleBorderRadius = 1;
            this.num3.IdleBorderThickness = 1;
            this.num3.IdleFillColor = System.Drawing.Color.DimGray;
            this.num3.IdleIconLeftImage = null;
            this.num3.IdleIconRightImage = null;
            this.num3.IndicateFocus = true;
            this.num3.Location = new System.Drawing.Point(198, 276);
            this.num3.Name = "num3";
            stateProperties173.BorderColor = System.Drawing.Color.DimGray;
            stateProperties173.BorderRadius = 1;
            stateProperties173.BorderThickness = 1;
            stateProperties173.FillColor = System.Drawing.Color.DimGray;
            stateProperties173.ForeColor = System.Drawing.Color.White;
            stateProperties173.IconLeftImage = null;
            stateProperties173.IconRightImage = null;
            this.num3.onHoverState = stateProperties173;
            stateProperties174.BorderColor = System.Drawing.Color.DimGray;
            stateProperties174.BorderRadius = 1;
            stateProperties174.BorderThickness = 1;
            stateProperties174.FillColor = System.Drawing.Color.DimGray;
            stateProperties174.ForeColor = System.Drawing.Color.White;
            stateProperties174.IconLeftImage = null;
            stateProperties174.IconRightImage = null;
            this.num3.OnPressedState = stateProperties174;
            this.num3.Size = new System.Drawing.Size(100, 100);
            this.num3.TabIndex = 12;
            this.num3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num3.TextMarginLeft = 0;
            this.num3.Click += new System.EventHandler(this.Num3_Click);
            // 
            // close_btn
            // 
            this.close_btn.AnimationSpeed = 220;
            this.close_btn.BackColor = System.Drawing.Color.Transparent;
            this.close_btn.BackColor1 = System.Drawing.Color.Teal;
            this.close_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("close_btn.BackgroundImage")));
            this.close_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.close_btn.ButtonText = "<";
            this.close_btn.ButtonTextMarginLeft = 0;
            this.close_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.close_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.close_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.close_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.close_btn.DisabledForecolor = System.Drawing.Color.White;
            this.close_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.close_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.close_btn.ForeColor = System.Drawing.Color.White;
            this.close_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.close_btn.IconPadding = 10;
            this.close_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.close_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.close_btn.IdleBorderRadius = 1;
            this.close_btn.IdleBorderThickness = 1;
            this.close_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.close_btn.IdleIconLeftImage = null;
            this.close_btn.IdleIconRightImage = null;
            this.close_btn.IndicateFocus = true;
            this.close_btn.Location = new System.Drawing.Point(297, 177);
            this.close_btn.Name = "close_btn";
            stateProperties175.BorderColor = System.Drawing.Color.Teal;
            stateProperties175.BorderRadius = 1;
            stateProperties175.BorderThickness = 1;
            stateProperties175.FillColor = System.Drawing.Color.Teal;
            stateProperties175.ForeColor = System.Drawing.Color.White;
            stateProperties175.IconLeftImage = null;
            stateProperties175.IconRightImage = null;
            this.close_btn.onHoverState = stateProperties175;
            stateProperties176.BorderColor = System.Drawing.Color.Teal;
            stateProperties176.BorderRadius = 1;
            stateProperties176.BorderThickness = 1;
            stateProperties176.FillColor = System.Drawing.Color.Teal;
            stateProperties176.ForeColor = System.Drawing.Color.White;
            stateProperties176.IconLeftImage = null;
            stateProperties176.IconRightImage = null;
            this.close_btn.OnPressedState = stateProperties176;
            this.close_btn.Size = new System.Drawing.Size(100, 100);
            this.close_btn.TabIndex = 1;
            this.close_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.close_btn.TextMarginLeft = 0;
            this.close_btn.Click += new System.EventHandler(this.Close_btn_Click);
            // 
            // CE_btn
            // 
            this.CE_btn.AnimationSpeed = 220;
            this.CE_btn.BackColor = System.Drawing.Color.Transparent;
            this.CE_btn.BackColor1 = System.Drawing.Color.Teal;
            this.CE_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CE_btn.BackgroundImage")));
            this.CE_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.CE_btn.ButtonText = "CE";
            this.CE_btn.ButtonTextMarginLeft = 0;
            this.CE_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.CE_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CE_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.CE_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.CE_btn.DisabledForecolor = System.Drawing.Color.White;
            this.CE_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CE_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 36F, System.Drawing.FontStyle.Bold);
            this.CE_btn.ForeColor = System.Drawing.Color.White;
            this.CE_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.CE_btn.IconPadding = 10;
            this.CE_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.CE_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.CE_btn.IdleBorderRadius = 1;
            this.CE_btn.IdleBorderThickness = 1;
            this.CE_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.CE_btn.IdleIconLeftImage = null;
            this.CE_btn.IdleIconRightImage = null;
            this.CE_btn.IndicateFocus = true;
            this.CE_btn.Location = new System.Drawing.Point(198, 177);
            this.CE_btn.Name = "CE_btn";
            stateProperties177.BorderColor = System.Drawing.Color.Teal;
            stateProperties177.BorderRadius = 1;
            stateProperties177.BorderThickness = 1;
            stateProperties177.FillColor = System.Drawing.Color.Teal;
            stateProperties177.ForeColor = System.Drawing.Color.White;
            stateProperties177.IconLeftImage = null;
            stateProperties177.IconRightImage = null;
            this.CE_btn.onHoverState = stateProperties177;
            stateProperties178.BorderColor = System.Drawing.Color.Teal;
            stateProperties178.BorderRadius = 1;
            stateProperties178.BorderThickness = 1;
            stateProperties178.FillColor = System.Drawing.Color.Teal;
            stateProperties178.ForeColor = System.Drawing.Color.White;
            stateProperties178.IconLeftImage = null;
            stateProperties178.IconRightImage = null;
            this.CE_btn.OnPressedState = stateProperties178;
            this.CE_btn.Size = new System.Drawing.Size(100, 100);
            this.CE_btn.TabIndex = 10;
            this.CE_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CE_btn.TextMarginLeft = 0;
            this.CE_btn.Click += new System.EventHandler(this.CE_btn_Click);
            // 
            // C_btn
            // 
            this.C_btn.AnimationSpeed = 220;
            this.C_btn.BackColor = System.Drawing.Color.Transparent;
            this.C_btn.BackColor1 = System.Drawing.Color.Teal;
            this.C_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("C_btn.BackgroundImage")));
            this.C_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.C_btn.ButtonText = "C";
            this.C_btn.ButtonTextMarginLeft = 0;
            this.C_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.C_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.C_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.C_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.C_btn.DisabledForecolor = System.Drawing.Color.White;
            this.C_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.C_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.C_btn.ForeColor = System.Drawing.Color.White;
            this.C_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.C_btn.IconPadding = 10;
            this.C_btn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.C_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.C_btn.IdleBorderRadius = 1;
            this.C_btn.IdleBorderThickness = 1;
            this.C_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.C_btn.IdleIconLeftImage = null;
            this.C_btn.IdleIconRightImage = null;
            this.C_btn.IndicateFocus = true;
            this.C_btn.Location = new System.Drawing.Point(99, 177);
            this.C_btn.Name = "C_btn";
            stateProperties179.BorderColor = System.Drawing.Color.Teal;
            stateProperties179.BorderRadius = 1;
            stateProperties179.BorderThickness = 1;
            stateProperties179.FillColor = System.Drawing.Color.Teal;
            stateProperties179.ForeColor = System.Drawing.Color.White;
            stateProperties179.IconLeftImage = null;
            stateProperties179.IconRightImage = null;
            this.C_btn.onHoverState = stateProperties179;
            stateProperties180.BorderColor = System.Drawing.Color.Teal;
            stateProperties180.BorderRadius = 1;
            stateProperties180.BorderThickness = 1;
            stateProperties180.FillColor = System.Drawing.Color.Teal;
            stateProperties180.ForeColor = System.Drawing.Color.White;
            stateProperties180.IconLeftImage = null;
            stateProperties180.IconRightImage = null;
            this.C_btn.OnPressedState = stateProperties180;
            this.C_btn.Size = new System.Drawing.Size(100, 100);
            this.C_btn.TabIndex = 10;
            this.C_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.C_btn.TextMarginLeft = 0;
            this.C_btn.Click += new System.EventHandler(this.C_btn_Click);
            // 
            // Quotient_btn
            // 
            this.Quotient_btn.AnimationSpeed = 220;
            this.Quotient_btn.BackColor = System.Drawing.Color.Transparent;
            this.Quotient_btn.BackColor1 = System.Drawing.Color.Teal;
            this.Quotient_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Quotient_btn.BackgroundImage")));
            this.Quotient_btn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.Quotient_btn.ButtonText = "%";
            this.Quotient_btn.ButtonTextMarginLeft = 0;
            this.Quotient_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Quotient_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Quotient_btn.DisabledBorderColor = System.Drawing.Color.Teal;
            this.Quotient_btn.DisabledFillColor = System.Drawing.Color.Teal;
            this.Quotient_btn.DisabledForecolor = System.Drawing.Color.White;
            this.Quotient_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Quotient_btn.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Quotient_btn.ForeColor = System.Drawing.Color.White;
            this.Quotient_btn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Quotient_btn.IconPadding = 10;
            this.Quotient_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Quotient_btn.IdleBorderColor = System.Drawing.Color.Teal;
            this.Quotient_btn.IdleBorderRadius = 1;
            this.Quotient_btn.IdleBorderThickness = 1;
            this.Quotient_btn.IdleFillColor = System.Drawing.Color.Teal;
            this.Quotient_btn.IdleIconLeftImage = null;
            this.Quotient_btn.IdleIconRightImage = null;
            this.Quotient_btn.IndicateFocus = true;
            this.Quotient_btn.Location = new System.Drawing.Point(0, 177);
            this.Quotient_btn.Name = "Quotient_btn";
            stateProperties181.BorderColor = System.Drawing.Color.Teal;
            stateProperties181.BorderRadius = 1;
            stateProperties181.BorderThickness = 1;
            stateProperties181.FillColor = System.Drawing.Color.Teal;
            stateProperties181.ForeColor = System.Drawing.Color.White;
            stateProperties181.IconLeftImage = null;
            stateProperties181.IconRightImage = null;
            this.Quotient_btn.onHoverState = stateProperties181;
            stateProperties182.BorderColor = System.Drawing.Color.Teal;
            stateProperties182.BorderRadius = 1;
            stateProperties182.BorderThickness = 1;
            stateProperties182.FillColor = System.Drawing.Color.Teal;
            stateProperties182.ForeColor = System.Drawing.Color.White;
            stateProperties182.IconLeftImage = null;
            stateProperties182.IconRightImage = null;
            this.Quotient_btn.OnPressedState = stateProperties182;
            this.Quotient_btn.Size = new System.Drawing.Size(100, 100);
            this.Quotient_btn.TabIndex = 9;
            this.Quotient_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Quotient_btn.TextMarginLeft = 0;
            this.Quotient_btn.Click += new System.EventHandler(this.Quotient_btn_Click);
            // 
            // num8
            // 
            this.num8.AnimationSpeed = 220;
            this.num8.BackColor = System.Drawing.Color.Transparent;
            this.num8.BackColor1 = System.Drawing.Color.DimGray;
            this.num8.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num8.BackgroundImage")));
            this.num8.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num8.ButtonText = "8";
            this.num8.ButtonTextMarginLeft = 0;
            this.num8.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num8.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num8.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num8.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num8.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num8.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num8.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num8.ForeColor = System.Drawing.Color.White;
            this.num8.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num8.IconPadding = 10;
            this.num8.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num8.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num8.IdleBorderRadius = 1;
            this.num8.IdleBorderThickness = 1;
            this.num8.IdleFillColor = System.Drawing.Color.DimGray;
            this.num8.IdleIconLeftImage = null;
            this.num8.IdleIconRightImage = null;
            this.num8.IndicateFocus = true;
            this.num8.Location = new System.Drawing.Point(99, 474);
            this.num8.Name = "num8";
            stateProperties183.BorderColor = System.Drawing.Color.DimGray;
            stateProperties183.BorderRadius = 1;
            stateProperties183.BorderThickness = 1;
            stateProperties183.FillColor = System.Drawing.Color.DimGray;
            stateProperties183.ForeColor = System.Drawing.Color.White;
            stateProperties183.IconLeftImage = null;
            stateProperties183.IconRightImage = null;
            this.num8.onHoverState = stateProperties183;
            stateProperties184.BorderColor = System.Drawing.Color.DimGray;
            stateProperties184.BorderRadius = 1;
            stateProperties184.BorderThickness = 1;
            stateProperties184.FillColor = System.Drawing.Color.DimGray;
            stateProperties184.ForeColor = System.Drawing.Color.White;
            stateProperties184.IconLeftImage = null;
            stateProperties184.IconRightImage = null;
            this.num8.OnPressedState = stateProperties184;
            this.num8.Size = new System.Drawing.Size(100, 100);
            this.num8.TabIndex = 6;
            this.num8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num8.TextMarginLeft = 0;
            this.num8.Click += new System.EventHandler(this.Num8_Click);
            // 
            // num6
            // 
            this.num6.AnimationSpeed = 220;
            this.num6.BackColor = System.Drawing.Color.Transparent;
            this.num6.BackColor1 = System.Drawing.Color.DimGray;
            this.num6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num6.BackgroundImage")));
            this.num6.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num6.ButtonText = "6";
            this.num6.ButtonTextMarginLeft = 0;
            this.num6.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num6.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num6.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num6.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num6.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num6.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num6.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num6.ForeColor = System.Drawing.Color.White;
            this.num6.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num6.IconPadding = 10;
            this.num6.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num6.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num6.IdleBorderRadius = 1;
            this.num6.IdleBorderThickness = 1;
            this.num6.IdleFillColor = System.Drawing.Color.DimGray;
            this.num6.IdleIconLeftImage = null;
            this.num6.IdleIconRightImage = null;
            this.num6.IndicateFocus = true;
            this.num6.Location = new System.Drawing.Point(198, 375);
            this.num6.Name = "num6";
            stateProperties185.BorderColor = System.Drawing.Color.DimGray;
            stateProperties185.BorderRadius = 1;
            stateProperties185.BorderThickness = 1;
            stateProperties185.FillColor = System.Drawing.Color.DimGray;
            stateProperties185.ForeColor = System.Drawing.Color.White;
            stateProperties185.IconLeftImage = null;
            stateProperties185.IconRightImage = null;
            this.num6.onHoverState = stateProperties185;
            stateProperties186.BorderColor = System.Drawing.Color.DimGray;
            stateProperties186.BorderRadius = 1;
            stateProperties186.BorderThickness = 1;
            stateProperties186.FillColor = System.Drawing.Color.DimGray;
            stateProperties186.ForeColor = System.Drawing.Color.White;
            stateProperties186.IconLeftImage = null;
            stateProperties186.IconRightImage = null;
            this.num6.OnPressedState = stateProperties186;
            this.num6.Size = new System.Drawing.Size(100, 100);
            this.num6.TabIndex = 6;
            this.num6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num6.TextMarginLeft = 0;
            this.num6.Click += new System.EventHandler(this.Num6_Click);
            // 
            // num4
            // 
            this.num4.AnimationSpeed = 220;
            this.num4.BackColor = System.Drawing.Color.Transparent;
            this.num4.BackColor1 = System.Drawing.Color.DimGray;
            this.num4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num4.BackgroundImage")));
            this.num4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num4.ButtonText = "4";
            this.num4.ButtonTextMarginLeft = 0;
            this.num4.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num4.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num4.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num4.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num4.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num4.ForeColor = System.Drawing.Color.White;
            this.num4.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num4.IconPadding = 10;
            this.num4.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num4.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num4.IdleBorderRadius = 1;
            this.num4.IdleBorderThickness = 1;
            this.num4.IdleFillColor = System.Drawing.Color.DimGray;
            this.num4.IdleIconLeftImage = null;
            this.num4.IdleIconRightImage = null;
            this.num4.IndicateFocus = true;
            this.num4.Location = new System.Drawing.Point(0, 375);
            this.num4.Name = "num4";
            stateProperties187.BorderColor = System.Drawing.Color.DimGray;
            stateProperties187.BorderRadius = 1;
            stateProperties187.BorderThickness = 1;
            stateProperties187.FillColor = System.Drawing.Color.DimGray;
            stateProperties187.ForeColor = System.Drawing.Color.White;
            stateProperties187.IconLeftImage = null;
            stateProperties187.IconRightImage = null;
            this.num4.onHoverState = stateProperties187;
            stateProperties188.BorderColor = System.Drawing.Color.DimGray;
            stateProperties188.BorderRadius = 1;
            stateProperties188.BorderThickness = 1;
            stateProperties188.FillColor = System.Drawing.Color.DimGray;
            stateProperties188.ForeColor = System.Drawing.Color.White;
            stateProperties188.IconLeftImage = null;
            stateProperties188.IconRightImage = null;
            this.num4.OnPressedState = stateProperties188;
            this.num4.Size = new System.Drawing.Size(100, 100);
            this.num4.TabIndex = 5;
            this.num4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num4.TextMarginLeft = 0;
            this.num4.Click += new System.EventHandler(this.Num4_Click);
            // 
            // num5
            // 
            this.num5.AnimationSpeed = 220;
            this.num5.BackColor = System.Drawing.Color.Transparent;
            this.num5.BackColor1 = System.Drawing.Color.DimGray;
            this.num5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num5.BackgroundImage")));
            this.num5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num5.ButtonText = "5";
            this.num5.ButtonTextMarginLeft = 0;
            this.num5.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num5.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num5.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num5.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num5.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num5.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num5.ForeColor = System.Drawing.Color.White;
            this.num5.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num5.IconPadding = 10;
            this.num5.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num5.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num5.IdleBorderRadius = 1;
            this.num5.IdleBorderThickness = 1;
            this.num5.IdleFillColor = System.Drawing.Color.DimGray;
            this.num5.IdleIconLeftImage = null;
            this.num5.IdleIconRightImage = null;
            this.num5.IndicateFocus = true;
            this.num5.Location = new System.Drawing.Point(99, 375);
            this.num5.Name = "num5";
            stateProperties189.BorderColor = System.Drawing.Color.DimGray;
            stateProperties189.BorderRadius = 1;
            stateProperties189.BorderThickness = 1;
            stateProperties189.FillColor = System.Drawing.Color.DimGray;
            stateProperties189.ForeColor = System.Drawing.Color.White;
            stateProperties189.IconLeftImage = null;
            stateProperties189.IconRightImage = null;
            this.num5.onHoverState = stateProperties189;
            stateProperties190.BorderColor = System.Drawing.Color.DimGray;
            stateProperties190.BorderRadius = 1;
            stateProperties190.BorderThickness = 1;
            stateProperties190.FillColor = System.Drawing.Color.DimGray;
            stateProperties190.ForeColor = System.Drawing.Color.White;
            stateProperties190.IconLeftImage = null;
            stateProperties190.IconRightImage = null;
            this.num5.OnPressedState = stateProperties190;
            this.num5.Size = new System.Drawing.Size(100, 100);
            this.num5.TabIndex = 4;
            this.num5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num5.TextMarginLeft = 0;
            this.num5.Click += new System.EventHandler(this.Num5_Click);
            // 
            // num1
            // 
            this.num1.AnimationSpeed = 220;
            this.num1.BackColor = System.Drawing.Color.Transparent;
            this.num1.BackColor1 = System.Drawing.Color.DimGray;
            this.num1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num1.BackgroundImage")));
            this.num1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num1.ButtonText = "1";
            this.num1.ButtonTextMarginLeft = 0;
            this.num1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num1.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num1.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num1.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num1.ForeColor = System.Drawing.Color.White;
            this.num1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num1.IconPadding = 10;
            this.num1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num1.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num1.IdleBorderRadius = 1;
            this.num1.IdleBorderThickness = 1;
            this.num1.IdleFillColor = System.Drawing.Color.DimGray;
            this.num1.IdleIconLeftImage = null;
            this.num1.IdleIconRightImage = null;
            this.num1.IndicateFocus = true;
            this.num1.Location = new System.Drawing.Point(0, 276);
            this.num1.Name = "num1";
            stateProperties191.BorderColor = System.Drawing.Color.DimGray;
            stateProperties191.BorderRadius = 1;
            stateProperties191.BorderThickness = 1;
            stateProperties191.FillColor = System.Drawing.Color.DimGray;
            stateProperties191.ForeColor = System.Drawing.Color.White;
            stateProperties191.IconLeftImage = null;
            stateProperties191.IconRightImage = null;
            this.num1.onHoverState = stateProperties191;
            stateProperties192.BorderColor = System.Drawing.Color.DimGray;
            stateProperties192.BorderRadius = 1;
            stateProperties192.BorderThickness = 1;
            stateProperties192.FillColor = System.Drawing.Color.DimGray;
            stateProperties192.ForeColor = System.Drawing.Color.White;
            stateProperties192.IconLeftImage = null;
            stateProperties192.IconRightImage = null;
            this.num1.OnPressedState = stateProperties192;
            this.num1.Size = new System.Drawing.Size(100, 100);
            this.num1.TabIndex = 2;
            this.num1.Tag = "";
            this.num1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num1.TextMarginLeft = 0;
            this.num1.Click += new System.EventHandler(this.Num1_Click);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = false;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = false;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = this.panel1;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // num7
            // 
            this.num7.AnimationSpeed = 220;
            this.num7.BackColor = System.Drawing.Color.Transparent;
            this.num7.BackColor1 = System.Drawing.Color.DimGray;
            this.num7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num7.BackgroundImage")));
            this.num7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num7.ButtonText = "7";
            this.num7.ButtonTextMarginLeft = 0;
            this.num7.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num7.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num7.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num7.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num7.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num7.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num7.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num7.ForeColor = System.Drawing.Color.White;
            this.num7.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num7.IconPadding = 10;
            this.num7.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num7.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num7.IdleBorderRadius = 1;
            this.num7.IdleBorderThickness = 1;
            this.num7.IdleFillColor = System.Drawing.Color.DimGray;
            this.num7.IdleIconLeftImage = null;
            this.num7.IdleIconRightImage = null;
            this.num7.IndicateFocus = true;
            this.num7.Location = new System.Drawing.Point(0, 474);
            this.num7.Name = "num7";
            stateProperties199.BorderColor = System.Drawing.Color.DimGray;
            stateProperties199.BorderRadius = 1;
            stateProperties199.BorderThickness = 1;
            stateProperties199.FillColor = System.Drawing.Color.DimGray;
            stateProperties199.ForeColor = System.Drawing.Color.White;
            stateProperties199.IconLeftImage = null;
            stateProperties199.IconRightImage = null;
            this.num7.onHoverState = stateProperties199;
            stateProperties200.BorderColor = System.Drawing.Color.DimGray;
            stateProperties200.BorderRadius = 1;
            stateProperties200.BorderThickness = 1;
            stateProperties200.FillColor = System.Drawing.Color.DimGray;
            stateProperties200.ForeColor = System.Drawing.Color.White;
            stateProperties200.IconLeftImage = null;
            stateProperties200.IconRightImage = null;
            this.num7.OnPressedState = stateProperties200;
            this.num7.Size = new System.Drawing.Size(100, 100);
            this.num7.TabIndex = 21;
            this.num7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num7.TextMarginLeft = 0;
            this.num7.Click += new System.EventHandler(this.Num7_Click);
            // 
            // num2
            // 
            this.num2.AnimationSpeed = 220;
            this.num2.BackColor = System.Drawing.Color.Transparent;
            this.num2.BackColor1 = System.Drawing.Color.DimGray;
            this.num2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num2.BackgroundImage")));
            this.num2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num2.ButtonText = "2";
            this.num2.ButtonTextMarginLeft = 0;
            this.num2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num2.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num2.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num2.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num2.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num2.ForeColor = System.Drawing.Color.White;
            this.num2.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num2.IconPadding = 10;
            this.num2.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num2.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num2.IdleBorderRadius = 1;
            this.num2.IdleBorderThickness = 1;
            this.num2.IdleFillColor = System.Drawing.Color.DimGray;
            this.num2.IdleIconLeftImage = null;
            this.num2.IdleIconRightImage = null;
            this.num2.IndicateFocus = true;
            this.num2.Location = new System.Drawing.Point(99, 276);
            this.num2.Name = "num2";
            stateProperties197.BorderColor = System.Drawing.Color.DimGray;
            stateProperties197.BorderRadius = 1;
            stateProperties197.BorderThickness = 1;
            stateProperties197.FillColor = System.Drawing.Color.DimGray;
            stateProperties197.ForeColor = System.Drawing.Color.White;
            stateProperties197.IconLeftImage = null;
            stateProperties197.IconRightImage = null;
            this.num2.onHoverState = stateProperties197;
            stateProperties198.BorderColor = System.Drawing.Color.DimGray;
            stateProperties198.BorderRadius = 1;
            stateProperties198.BorderThickness = 1;
            stateProperties198.FillColor = System.Drawing.Color.DimGray;
            stateProperties198.ForeColor = System.Drawing.Color.White;
            stateProperties198.IconLeftImage = null;
            stateProperties198.IconRightImage = null;
            this.num2.OnPressedState = stateProperties198;
            this.num2.Size = new System.Drawing.Size(100, 100);
            this.num2.TabIndex = 22;
            this.num2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num2.TextMarginLeft = 0;
            this.num2.Click += new System.EventHandler(this.Num2_Click);
            // 
            // num9
            // 
            this.num9.AnimationSpeed = 220;
            this.num9.BackColor = System.Drawing.Color.Transparent;
            this.num9.BackColor1 = System.Drawing.Color.DimGray;
            this.num9.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num9.BackgroundImage")));
            this.num9.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num9.ButtonText = "9";
            this.num9.ButtonTextMarginLeft = 0;
            this.num9.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num9.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num9.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num9.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num9.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num9.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num9.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num9.ForeColor = System.Drawing.Color.White;
            this.num9.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num9.IconPadding = 10;
            this.num9.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num9.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num9.IdleBorderRadius = 1;
            this.num9.IdleBorderThickness = 1;
            this.num9.IdleFillColor = System.Drawing.Color.DimGray;
            this.num9.IdleIconLeftImage = null;
            this.num9.IdleIconRightImage = null;
            this.num9.IndicateFocus = true;
            this.num9.Location = new System.Drawing.Point(198, 474);
            this.num9.Name = "num9";
            stateProperties195.BorderColor = System.Drawing.Color.DimGray;
            stateProperties195.BorderRadius = 1;
            stateProperties195.BorderThickness = 1;
            stateProperties195.FillColor = System.Drawing.Color.DimGray;
            stateProperties195.ForeColor = System.Drawing.Color.White;
            stateProperties195.IconLeftImage = null;
            stateProperties195.IconRightImage = null;
            this.num9.onHoverState = stateProperties195;
            stateProperties196.BorderColor = System.Drawing.Color.DimGray;
            stateProperties196.BorderRadius = 1;
            stateProperties196.BorderThickness = 1;
            stateProperties196.FillColor = System.Drawing.Color.DimGray;
            stateProperties196.ForeColor = System.Drawing.Color.White;
            stateProperties196.IconLeftImage = null;
            stateProperties196.IconRightImage = null;
            this.num9.OnPressedState = stateProperties196;
            this.num9.Size = new System.Drawing.Size(100, 100);
            this.num9.TabIndex = 23;
            this.num9.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num9.TextMarginLeft = 0;
            this.num9.Click += new System.EventHandler(this.Num9_Click);
            // 
            // num0
            // 
            this.num0.AnimationSpeed = 220;
            this.num0.BackColor = System.Drawing.Color.Transparent;
            this.num0.BackColor1 = System.Drawing.Color.DimGray;
            this.num0.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("num0.BackgroundImage")));
            this.num0.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.num0.ButtonText = "0";
            this.num0.ButtonTextMarginLeft = 0;
            this.num0.Cursor = System.Windows.Forms.Cursors.Hand;
            this.num0.DialogResult = System.Windows.Forms.DialogResult.None;
            this.num0.DisabledBorderColor = System.Drawing.Color.DimGray;
            this.num0.DisabledFillColor = System.Drawing.Color.DimGray;
            this.num0.DisabledForecolor = System.Drawing.Color.DimGray;
            this.num0.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.num0.Font = new System.Drawing.Font("Arial Rounded MT Bold", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num0.ForeColor = System.Drawing.Color.White;
            this.num0.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.num0.IconPadding = 10;
            this.num0.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.num0.IdleBorderColor = System.Drawing.Color.DimGray;
            this.num0.IdleBorderRadius = 1;
            this.num0.IdleBorderThickness = 1;
            this.num0.IdleFillColor = System.Drawing.Color.DimGray;
            this.num0.IdleIconLeftImage = null;
            this.num0.IdleIconRightImage = null;
            this.num0.IndicateFocus = true;
            this.num0.Location = new System.Drawing.Point(99, 573);
            this.num0.Name = "num0";
            stateProperties193.BorderColor = System.Drawing.Color.DimGray;
            stateProperties193.BorderRadius = 1;
            stateProperties193.BorderThickness = 1;
            stateProperties193.FillColor = System.Drawing.Color.DimGray;
            stateProperties193.ForeColor = System.Drawing.Color.White;
            stateProperties193.IconLeftImage = null;
            stateProperties193.IconRightImage = null;
            this.num0.onHoverState = stateProperties193;
            stateProperties194.BorderColor = System.Drawing.Color.DimGray;
            stateProperties194.BorderRadius = 1;
            stateProperties194.BorderThickness = 1;
            stateProperties194.FillColor = System.Drawing.Color.DimGray;
            stateProperties194.ForeColor = System.Drawing.Color.White;
            stateProperties194.IconLeftImage = null;
            stateProperties194.IconRightImage = null;
            this.num0.OnPressedState = stateProperties194;
            this.num0.Size = new System.Drawing.Size(100, 100);
            this.num0.TabIndex = 24;
            this.num0.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.num0.TextMarginLeft = 0;
            this.num0.Click += new System.EventHandler(this.Num0_Click);
            // 
            // label3
            // 
            this.label3.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.label3.Font = new System.Drawing.Font("Verdana", 18F);
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(78, 54);
            this.label3.Name = "label3";
            this.label3.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label3.Size = new System.Drawing.Size(306, 32);
            this.label3.TabIndex = 25;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ClientSize = new System.Drawing.Size(396, 671);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.num0);
            this.Controls.Add(this.num9);
            this.Controls.Add(this.num2);
            this.Controls.Add(this.num7);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.equal_btn);
            this.Controls.Add(this.Multiply_btn);
            this.Controls.Add(this.Less_btn);
            this.Controls.Add(this.double_btn);
            this.Controls.Add(this.Divide_btn);
            this.Controls.Add(this.add_btn);
            this.Controls.Add(this.num3);
            this.Controls.Add(this.close_btn);
            this.Controls.Add(this.CE_btn);
            this.Controls.Add(this.C_btn);
            this.Controls.Add(this.Quotient_btn);
            this.Controls.Add(this.num8);
            this.Controls.Add(this.num6);
            this.Controls.Add(this.num4);
            this.Controls.Add(this.num5);
            this.Controls.Add(this.num1);
            this.Controls.Add(this.panel1);
            this.Font = new System.Drawing.Font("微軟正黑體", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(136)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(5);
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Quotient_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton C_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CE_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton close_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton add_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Divide_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton double_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Less_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Multiply_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton equal_btn;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num0;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton num9;
        private System.Windows.Forms.Label label3;
    }
}

